export const SET_ALL_CAPSULES = 'SET_ALL_CAPSULES';
export const SET_UPCOMING_CAPSULES = 'SET_UPCOMING_CAPSULES';
export const SET_PAST_CAPSULES = 'SET_PAST_CAPSULES';
export const SET_CAPSULE = 'SET_CAPSULE';