export const SET_ALL_LAUNCHES = 'SET_ALL_LAUNCHES';
export const SET_UPCOMING_LAUNCHES = 'SET_UPCOMING_LAUNCHES';
export const SET_PAST_LAUNCHES = 'SET_PAST_LAUNCHES';
export const SET_LAUNCH = 'SET_LAUNCH';
export const SET_LATEST_LAUNCH = 'SET_LATEST_LAUNCH';
export const SET_NEXT_LAUNCH = 'SET_NEXT_LAUNCH';